Add tags resource
rickwest/laravel-wordpress-api pull request #9
Opened 2023-07-18 06:18 UTC by DevProsanta

2023-08-26 00:32 UTC, rickwest commented on src/WordPress.php
> + * @method tags tags()
Just one tiny comment - could you uppercase the class name here

2023-08-26 00:33 UTC, rickwest requested changes
Hey, thanks for the pull request! I've just left one tiny comment but other than that it looks good to go! Thank you 🙏🏻

2023-11-18 08:49 UTC, NazimNasser commented
@rickwest can we please merge this?

2023-11-29 16:25 UTC, merged

2023-11-29 17:12 UTC, rickwest commented
Thats for the contribution @DevProsanta